In [1]:
import csv
import numpy as np 
import random
import time
# sve_ivp
import os
import pandas as pd
import matplotlib.pyplot as plt
from os.path import dirname, realpath, sep, pardir
import sys

In [8]:
## hpg path on mac 
# data_path = "/Volumes/hodaakl/"
## hpg path on thinkpad 
data_path = "//exasmb.rc.ufl.edu/blue/pdixit/hodaakl/"
## hpg path on hpg 
# data_path = "/blue/pdixit/hodaakl/"
# specify the project you are working on     
spec_folder = data_path + 'A1MAXENT_EGF/Code/Percentile_Constraints/'
# sys.path.append(data_path + 'A1MAXENT_EGF/Code/Percentile_Constraints/')
folder_out = 'Output_0504/'
path = spec_folder + folder_out


In [9]:
from UPDATE_LM_FNS import calculate_constraints, update_lambda, openfile
from PREDICTION_FUNCTIONS import cell_pred_fn

In [10]:
#### load the parameters - cell 1 - iteration 142 
iteration = 142
par_fn = path + f'/params_{iteration}.csv'
df = pd.read_csv(par_fn, sep = ',', header = None) 
pardat = df.to_numpy()

In [47]:
c0 = pardat[0,:]
c0.shape
Larr = np.load(f'{spec_folder}/ArraysForMaxEnt/EGFR_doses_10Conditions_20201116.npy')

In [132]:
### seperate 
pardat.shape
l = 5
submat = pardat[:10,-l:]
np.savetxt("foo.csv", submat, delimiter=",")

In [135]:
# load foo
# par_fn = path + f'/params_{iteration}.csv'
dfn = pd.read_csv('foo.csv', sep = ',', header = None) 
mat = dfn.to_numpy()
mat == submat

array([[ True,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [ True,  True, False,  True,  True],
       [ True, False, False, False,  True],
       [False,  True, False, False,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False,  True, False, False,  True],
       [ True, False,  True,  True,  True],
       [False, False, False,  True,  True]])

In [140]:
mat[3,1]

0.048361153467293604

In [141]:
submat[3,1]

0.0483611534672936

### Debug the variance factor

In [109]:
## calculation 
means_ind , secmoms_ind  = cell_pred_fn(c0, Ligand_conc=[100.0])

100.0


In [125]:
means_arr_ind  = np.zeros(Larr.shape)
second_mom_ind = np.zeros(Larr.shape)
for i in range(Larr.shape[0]):
#     print(ligandconc)
    ligandconc = Larr[i]
    means_ind , secmoms_ind  = cell_pred_fn(c0, Ligand_conc=[ligandconc])
    means_arr_ind[i] = means_ind
    second_mom_ind[i]  = secmoms_ind
    print(means_ind)
    print(secmoms_ind)
    print(secmoms_ind - means_ind**2)
    print()

[0.0]
1
[0.]
[0.]
0.0
285397.9565092969
81452278977.63904
[285397.9565093]
[8.1452279e+10]
[285397.95651245]

[0.0078125]
1
[0.]
[0.]
0.0078125
238835.9609911063
57042855098.50625
[238835.96099111]
[5.70428551e+10]
[238835.96100616]

[0.015625]
1
[0.]
[0.]
0.015625
205951.93346003734
42416404847.86111
[205951.93346004]
[4.24164048e+10]
[205951.93345642]

[0.03125]
1
[0.]
[0.]
0.03125
162583.6268216143
26433598294.096767
[162583.62682161]
[2.64335983e+10]
[162583.62682343]

[0.0625]
1
[0.]
[0.]
0.0625
116478.38876076037
13567331526.69159
[116478.38876076]
[1.35673315e+10]
[116478.38876152]

[0.125]
1
[0.]
[0.]
0.125
77444.99191505178
5997804217.714351
[77444.99191505]
[5.99780422e+09]
[77444.99191475]

[0.25]
1
[0.]
[0.]
0.25
50279.81554031188
2528110130.5833282
[50279.81554031]
[2.52811013e+09]
[50279.81554031]

[0.5]
1
[0.]
[0.]
0.5
33849.77644074898
1145841214.865126
[33849.77644075]
[1.14584121e+09]
[33849.7764411]

[1.0]
1
[0.]
[0.]
1.0
24742.483407272994
612215227.6425868
[24742.4

In [126]:
print(means_arr_ind)
print(second_mom_ind)
print(second_mom_ind - (means_arr_ind**2))

[285397.9565093  238835.96099111 205951.93346004 162583.62682161
 116478.38876076  77444.99191505  50279.81554031  33849.77644075
  24742.48340727  15052.51464228]
[8.14522790e+10 5.70428551e+10 4.24164048e+10 2.64335983e+10
 1.35673315e+10 5.99780422e+09 2.52811013e+09 1.14584121e+09
 6.12215228e+08 2.26593250e+08]
[285397.95651245 238835.96100616 205951.93345642 162583.62682343
 116478.38876152  77444.99191475  50279.81554031  33849.7764411
  24742.48340738  15052.51464224]


In [127]:
means , secmoms  = cell_pred_fn(c0, Ligand_conc=Larr)

[0.0000e+00 7.8125e-03 1.5625e-02 3.1250e-02 6.2500e-02 1.2500e-01
 2.5000e-01 5.0000e-01 1.0000e+00 1.0000e+02]
10
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0
285397.9565092969
81452278977.63904
0.0078125
238835.9609911063
57042855098.50625
0.015625
205951.93346003734
42416404847.86111
0.03125
162583.6268216143
26433598294.096767
0.0625
116478.38876076037
13567331526.69159
0.125
77444.99191505178
5997804217.714351
0.25
50279.81554031188
2528110130.5833282
0.5
33849.77644074898
1145841214.865126
1.0
24742.483407272994
612215227.6425868
100.0
15052.51464228441
226593249.5708288


In [128]:
means == means_arr_ind 


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [129]:
second_mom_ind == secmoms

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [112]:
print(means)
print(secmoms)
print(secmoms - (means**2))

[285397.9565093  238835.96099111 205951.93346004 162583.62682161
 116478.38876076  77444.99191505  50279.81554031  33849.77644075
  24742.48340727  15052.51464228]
[8.14805334e+10 5.70664999e+10 4.24367941e+10 2.64496941e+10
 1.35788629e+10 6.00547127e+09 2.53308783e+09 1.14919234e+09
 6.14664733e+08 2.28083449e+08]
[28539795.65124512 23883596.10061646 20595193.34564209 16258362.68234253
 11647838.87615204  7744499.19147491  5027981.55403137  3384977.64410973
  2474248.34073782  1505251.46422386]


In [113]:
2.28083449e+08 - 15052.51464228**2

1505251.9439461827

In [95]:
secmoms_ind

array([2.2659325e+08])

In [79]:
secmoms

array([8.14805334e+10, 5.70664999e+10, 4.24367941e+10, 2.64496941e+10,
       1.35788629e+10, 6.00547127e+09, 2.53308783e+09, 1.14919234e+09,
       6.14664733e+08, 2.28083449e+08])

In [80]:
secmoms - (means**2)

array([28539795.65124512, 23883596.10061646, 20595193.34564209,
       16258362.68234253, 11647838.87615204,  7744499.19147491,
        5027981.55403137,  3384977.64410973,  2474248.34073782,
        1505251.46422386])

In [83]:
secmoms[-1]

228083448.52041042

In [92]:
means[-1]
means[-1]**2 == means_ind**2
secmoms[-1] == secmoms_ind 

array([False])

In [85]:
secmoms[-1] - ( means[-1]**2)

1505251.4642238617

In [87]:
secmoms_ind[0] -( means_ind[0]**2)

15052.514642238617

In [35]:
def segfr_preds(L,  pars_arr,n=1, SF = 0.00122 ):
    """ Obtains steady state predictions: the EGFR receptor numbers for a given Ligand concentration and Parameters vector 
    Inputs : L -> Ligand Concentration in nM 
            pars_arr -> Parameter vector : [ksyn, k1, kn1, kap, kdp, ki, kis]
                Pars array is of length 7 
            n -> noise factor 
            SF -> Conversion factor to change a.u. to molecules 
                The SF is to change from a.u. to molecules based on 305 a.u. = 250*10^3 molecules  )
    Outputs: mean and second moment after noise adjustmenet of the distribution of EGFR for that ligand concentration."""
    # idx = [16, 0, 1, 4, 5, 8, 9]
    [ksyn, k1, kn1, kap, kdp, ki, kis] = 10**pars_arr # parameters are in log scale!  
    ksyn = ksyn/SF
#     kap = kap/SF
    R0  = ksyn/ki
    mean= (ki* (kap* (kis+k1* L)+(kis+kdp) *(ki+kn1+k1* L))* R0)/(kap *kis* (ki+k1 *L)+ki *(kis+kdp) *(ki+kn1+k1*L))
    sec_mom = (ki*(kap *(kis+k1*L)+(kis+kdp)* (ki+kn1+k1*L)) *R0* (kap* kis* (ki+k1* L)+kap* ki* (kis+k1* L) *R0+ki* (kis+kdp)* (ki+kn1+k1* L)* (1+R0)))/(kap* kis* (ki+k1*L)+ki* (kis+kdp) *(ki+kn1+k1 *L))**2
    sec_mom_new = (sec_mom - mean**2)*(n**2) + mean**2 
    return mean, sec_mom_new

In [124]:
def cell_pred_fn(pars, Ligand_conc, n=1 ):
    """solves for all the ligand concentrations and returns the means and the second moments
    Inputs: pars: Parameter vector : [ksyn, k1, kn1, kap, kdp, ki, kis]
                Pars array is of length 7 
            Ligand_conc : array of ligand concentrations in nM  """
    print(Ligand_conc)
    n = len(Ligand_conc)
    print(n)
    means_arr = np.zeros(n)
    secmom_arr = np.zeros(n)
    print(means_arr)
    print(secmom_arr)
    for i in range(n): 
        L = Ligand_conc[i]
        print(L)
        mu, s = segfr_preds(L = L , pars_arr = pars,SF = 0.00122 )
        print(mu)
        print(s)
        means_arr[i] = mu
        secmom_arr[i] = s
    return means_arr, secmom_arr