In [4]:
alpha = 3 ; beta = 2

In [5]:
from scipy.stats import gamma 
import numpy as np
x = 10
gamma.cdf(x, a =alpha, scale = 1/beta)

0.9999995444850495

In [24]:
n = 100
a_arr = np.random.randint(3, 10,n)
b_arr = np.random.randint(3, 10,n)
x = np.random.randint(3, 100,n)
x = np.ones(n)*1
ans2 = []
ans1 = gamma.cdf(x, a =a_arr, scale = 1/b_arr)
for i in range(n):
    ans2.append(gamma.cdf(x[i], a =a_arr[i], scale = 1/b_arr[i]))
ans2 = np.asarray(ans2)
ans1==ans2
    
    
    
    

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [25]:
gamma.cdf(x, a =a_arr, scale = 1/b_arr)

array([0.98624603, 0.67610304, 0.35276811, 0.00380299, 0.82700839,
       0.27090873, 0.67610304, 0.5443474 , 0.08391794, 0.15276251,
       0.55028894, 0.76189669, 0.00380299, 0.55028894, 0.00380299,
       0.13337167, 0.00380299, 0.13337167, 0.55950671, 0.15276251,
       0.57680992, 0.23781654, 0.21486961, 0.37116306, 0.97877351,
       0.91823458, 0.9380312 , 0.69929172, 0.37116306, 0.13337167,
       0.91823458, 0.05113362, 0.5443474 , 0.06809363, 0.67610304,
       0.05113362, 0.73497408, 0.18473676, 0.05113362, 0.56652988,
       0.0119045 , 0.18473676, 0.76189669, 0.82700839, 0.35276811,
       0.76189669, 0.69929172, 0.69929172, 0.5443474 , 0.56652988,
       0.23781654, 0.97036384, 0.94503636, 0.98624603, 0.76189669,
       0.35276811, 0.35276811, 0.55950671, 0.68662572, 0.68662572,
       0.02136343, 0.40128616, 0.03350854, 0.76189669, 0.35276811,
       0.08391794, 0.05113362, 0.67610304, 0.27090873, 0.87534798,
       0.95761989, 0.55028894, 0.80876394, 0.95761989, 0.54434

In [1]:
# no need to integrate I could just use cdf 

In [7]:
import scipy.integrate as integrate
def integrand(y):
    out = gamma.pdf(y, a =alpha, scale = 1/beta)
    return out 

In [11]:
import numpy as np
alpha = np.array([1,2,4])
beta = np.array([4,3,4])
# integrate.quad(lambda y: gamma.pdf(y, a =alpha, scale = 1/beta), 0, np.inf)
gamma.cdf(x, a =alpha, scale = 1/beta)

array([1., 1., 1.])